version: '3'  # Docker Compose file version

services:  # Definition of services

  web:  # Service named 'web' for Django application

    build:  # Build configuration for Docker image
      context: .
      dockerfile: Dockerfile

    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  # Command to run when container starts

    container_name: django_app  # Name of the container

    volumes:  # Mounting volumes
      - .:/django_app  # Mounting current directory to /django_app in the container

    ports:  # Port mapping
      - "8000:8000"  # Expose port 8000 of the container to port 8000 of the host
